language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - yarn install

before_deploy:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
